
// Categories - Actions
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
// export const SET_CATEGORIES = 'SET_CATEGORIES';

// Transactions - Actions
export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';
// export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
// export const ADD_TRANSACTION = 'ADD_TRANSACTION';

// Current Transaction - Actions
export const SET_CURRTRANSACTION_AMOUNT = 'SET_CURRTRANSACTION_AMOUNT';
export const SET_CURRTRANSACTION_CATEGORY = 'SET_CURRTRANSACTION_CATEGORY';
export const SET_CURRTRANSACTION_DATE = 'SET_CURRTRANSACTION_DATE';
export const SET_CURRTRANSACTION_NOTE = 'SET_CURRTRANSACTION_NOTE';
export const RESET_CURRTRANSACTION = 'RESET_CURRTRANSACTION';

// SQLite - Actions
export const GET_SET_CATEGORIES = 'GET_SET_CATEGORIES';
export const GET_SET_TRANSACTIONS = 'GET_SET_TRANSACTIONS';
