
// Categories - Actions
export const SET_CATEGORIES = 'SET_CATEGORIES';

// Current Transaction - Actions
export const SET_CURRTRANSACTION_AMOUNT = 'SET_CURRTRANSACTION_AMOUNT';
export const SET_CURRTRANSACTION_CATEGORY = 'SET_CURRTRANSACTION_CATEGORY';
export const SET_CURRTRANSACTION_DATE = 'SET_CURRTRANSACTION_DATE';
export const SET_CURRTRANSACTION_NOTE = 'SET_CURRTRANSACTION_NOTE';