
// Wallets - Actions
export const ADD_WALLET = 'ADD_WALLET';
export const DELETE_WALLET = 'DELETE_WALLET';

// Current Wallet - Actions
export const SELECT_WALLET = 'SELECT_WALLET';

// Transactions - Actions
// export const GET_TRANSACTIONS = 'GET_TRANSACTION';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
// export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
// export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
// export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';

// Transactions Current Month - Actions
export const SET_TRANSACTIONS_CURR_MONTH = 'SET_TRANSACTIONS_CURR_MONTH';

// Current Transaction - Actions
export const SET_CURRTRANSACTION_ID = 'SET_CURRTRANSACTION_ID';
export const SET_CURRTRANSACTION_AMOUNT = 'SET_CURRTRANSACTION_AMOUNT';
export const SET_CURRTRANSACTION_CATEGORY = 'SET_CURRTRANSACTION_CATEGORY';
export const SET_CURRTRANSACTION_DATE = 'SET_CURRTRANSACTION_DATE';
export const SET_CURRTRANSACTION_NOTE = 'SET_CURRTRANSACTION_NOTE';
export const RESET_CURRTRANSACTION = 'RESET_CURRTRANSACTION';

// Categories - Actions
// export const GET_CATEGORIES = 'GET_CATEGORIES';
// export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
// export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
// export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
// export const SET_CATEGORIES = 'SET_CATEGORIES';

// Budgets - Actions
export const ADD_BUDGET = 'ADD_BUDGET';

// Current Budget - Actions
export const SET_CURRBUDGET_WALLET = 'SET_CURRBUDGET_WALLET';
export const SET_CURRBUDGET_NAME = 'SET_CURRBUDGET_NAME';
export const SET_CURRBUDGET_AMOUNT = 'SET_CURRBUDGET_AMOUNT';
export const SET_CURRBUDGET_CATEGORIES = 'SET_CURRBUDGET_CATEGORIES';
export const SET_CURRBUDGET_STARTDATE = 'SET_CURRBUDGET_STARTDATE';
export const SET_CURRBUDGET_ENDDATE = 'SET_CURRBUDGET_ENDDATE';
export const SET_CURRBUDGET_TYPE = 'SET_CURRBUDGET_TYPE';
export const SET_CURRBUDGET_REPEAT = 'SET_CURRBUDGET_REPEAT';


// Temp Categories Checkbox - Actions
export const ADD_CATEGORIES_CHECKBOX_CATEGORY = 'ADD_CATEGORIES_CHECKBOX_CATEGORY';
export const DELETE_CATEGORIES_CHECKBOX_CATEGORY = 'DELETE_CATEGORIES_CHECKBOX_CATEGORY';
export const SET_CATEGORIES_CHECKBOX_CATEGORIES = 'SET_CATEGORIES_CHECKBOX_CATEGORIES';
export const RESET_CATEGORIES_CHECKBOX_CATEGORIES = 'RESET_CATEGORIES_CHECKBOX_CATEGORIES';
